apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
spec:
  components:
  - name: example-app
    type: webservice
    properties:
      image: sselzer/example-app
      port: 8080
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            name: example-app
            key: OTEL_SERVICE_NAME
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: example-app
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            name: example-app
            key: PYROSCOPE_URL
    traits:
    - type: annotations
      properties:
        "prometheus.io/scrape": "true"
        "prometheus.io/path": /metrics
        "prometheus.io/port": "8080"
    - type: cpuscaler
      properties:
        min: 1
        max: 3
        cpuPercent: 80
    - type: gateway
      properties:
        domain: example-app.127.0.0.1.nip.io
        http:
          "/": 8080