apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-app-api
  description: API definition of example-app
spec:
  type: openapi
  owner: team-a
  lifecycle: production
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: example-app API
    servers:
    - url: https://example-app.127.0.0.1.nip.io
    paths:
      /:
        get:
          summary: Returns hello
